patent_analysis_task:
  description: >
    Perform an in-depth Natural Language Processing (NLP) analysis of the patent data
    (pre-loaded from a JSON knowledge source). Focus on:
    1.  Identifying core inventive concepts and the specific problem solved, paying close
        attention to semantic nuances and technical terminology.
    2.  Extracting key technical components, methodologies, and any mentioned algorithms
        or data structures using NLP techniques like Named Entity Recognition (NER) and
        relation extraction.
    3.  Pinpointing explicitly stated advantages, novel aspects, and potential applications,
        supported by textual evidence and sentiment analysis where applicable.
    4.  Summarizing any claims related to language understanding, generation, or processing
        if present in the patent.
  expected_output: >
    A structured, NLP-enhanced summary detailing:
    - The patent's core technology from an NLP perspective (e.g., text summarization,
      machine translation, sentiment analysis features if applicable).
    - The specific problem it addresses and the proposed linguistic/algorithmic solution.
    - Key distinguishing features and technical entities identified via NLP.
    - A concise list of claims or functionalities that leverage language processing.
    This summary will serve as context for the NLP-focused Product Strategist.
  agent: patent_analyst

product_creation_task:
  description: >
    Using the NLP-enhanced patent summary, develop a cutting-edge product concept that
    leverages the identified NLP capabilities. Your output must be a JSON object.
    Specifically, articulate:
    - product_title: A concise, compelling name for the NLP-powered product (up to 100 characters).
    - product_description: Explain the product, its core NLP features, target users (e.g.,
      researchers, developers, enterprises needing language solutions), their needs, and the
      unique benefits derived from its NLP technology (up to 300 characters).
    - implementation: Describe how the patent's core NLP methodologies or algorithms would be
      integrated into the product architecture to deliver its key features (up to 300 characters).
    - differentiation: Highlight what makes this NLP product unique. Focus on how its language
      processing capabilities (e.g., accuracy, specific domain adaptation, novel features identified
      through NLP analysis of the patent) set it apart from existing solutions (up to 300 characters).
  expected_output: >
    A JSON object containing:
    - publication_number (use "US-2020073983-A1")
    - title (product title reflecting its NLP nature)
    - product_description (emphasizing NLP features and benefits)
    - implementation (focusing on NLP technology integration)
    - differentiation (based on unique NLP capabilities or insights from the patent)
    The JSON structure should be exactly:
    {
      "publication_number": "US-2020073983-A1",
      "title": "<Your NLP Product Title>",
      "product_description": "<Your NLP Product Description>",
      "implementation": "<Your NLP Implementation Explanation>",
      "differentiation": "<Your NLP Differentiation Explanation>"
    }
  agent: product_manager
  context:
    - patent_analysis_task
  output_file: output/nlp/US-2020073983-A1_output.json 